# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This project aim to deal with modules related to the management
    of warehouses. Youll find modules that:\n - Ease inventory by adding various possibilities
    - Move all product from one location to another - Manage the product catalog (merge
    them,..)

    Please dont hesitate to suggest one of your module to this project. Also, you
    may want to have a look on those other projects here:

    - https://github.com/OCA/stock-logistics-tracking - https://github.com/OCA/stock-logistics-barcode
    - https://github.com/OCA/stock-logistics-workflow'
repo_name: stock-logistics-warehouse
repo_slug: stock-logistics-warehouse
repo_website: https://github.com/OCA/stock-logistics-warehouse
use_pyproject_toml: false
use_ruff: false

